### Here you can register new users, and login into application.
### Endpoint in other files require authorization

### register new user
POST https://{{host}}/user/register
Content-Type: application/json

{
  "username" : "testuser",
  "password": "testpassword"
}

### login
POST https://{{host}}/user/login
Content-Type: application/json

{
  "username" : "testuser",
  "password": "testpassword"
}

### logout
POST https://{{host}}/user/logout
Content-Type: application/json

{}